repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: sort-simple-yaml
  # - repo: local
  #   hooks:
  #     - id: detect-api-keys
  #       name: Detect API Keys
  #       entry: python readme_sync/tests/detect_secrets.py -p docs
  #       language: python
  #       always_run: true
  #       pass_filenames: false
  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
    -   id: black