repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: sort-simple-yaml
  - repo: local
    hooks:
      - id: detect-api-keys
        name: Detect API Keys
        entry: python scripts/detect_api_keys.py -p docs
        language: python
        always_run: true
        pass_filenames: false