docs:
- other:
  - data-privacy-policy.md
  - sdk-reference.md
- use-cases:
  - better-text-search:
    - better-text-search-prerequisites.md
    - fine-grained-search-search-on-chunks-of-text-data-2.md
    - better-text-search-with-hybrid.md
    - pure-word-matching-pure-vector-search-or-combination-of-both.md
    - better-text-search-diversified-search-results.md
    - pure-word-matching-pure-vector-search-or-combination-of-both-2.md
    - better-text-search-chunk-search.md
    - pure-word-matching-pure-vector-search-or-combination-of-both-1.md
    - fine-grained-search-search-on-chunks-of-text-data-1.md
    - fine-grained-search-search-on-chunks-of-text-data.md
  - vector-search:
    - multi-vector-search.md
    - filters.md
    - vector-search-prerequisites.md
    - hybrid-search.md
  - better-vector-visualisation:
    - prerequisites.md
  - image-search:
    - text-to-image-search.md
    - image-similarity-search.md
  - image-search.md
  - better-vector-visualisation.md
  - nlp-search-with-e-commerce.md
  - vector-search.md
  - better-text-search.md
- theory-and-concepts:
  - what-is-vector-search:
    - _applications-of-vectors.md
    - how-to-vector-search.md
    - _limitations-of-vectors.md
  - what-is-vector-search.md
  - vectors-for-classification.md
- general-features:
  - filters-1:
    - exact_match-1.md
    - exact_match.md
    - numeric.md
    - regex.md
    - categories.md
    - contains.md
    - date.md
    - multiple-filters.md
    - exists.md
    - or.md
    - combining-filters-and-vector-search.md
    - ids.md
  - how-to-vectorize:
    - _notebooks:
      - RelevanceAI_ReadMe_How_to_Vectorize.ipynb
    - vectorize-images.md
    - waiting-for-the-encoding-to-end.md
    - how-to-vectorize-text-using-vectorhub-transformers.md
    - vectorize-text.md
    - how-to-vectorize-using-the-sdk.md
  - aggregations:
    - _notebooks:
      - RelevanceAI_ReadMe_Quickstart_Aggregations.ipynb
    - creating-aggregation-metrics.md
    - grouping-the-data.md
    - aggregations-1.md
    - aggregation-quick-start.md
  - creating-a-dataset:
    - _notebooks:
      - RelevanceAI_ReadMe_Creating_A_Dataset.ipynb
      - RelevanceAI_ReadMe_Insert_A_CSV.ipynb
    - insert-a-csv.md
    - project-and-dataset.md
    - insert-a-df.md
    - ecommerce-example-dataset.md
    - documents-with-chunked-data.md
    - preparing-data-from-csv-pandas-df.md
    - inserting-data.md
  - multi-vector-search-3:
    - multi-vector-search-with.md
    - multi-vector-search-2.md
  - jsonshower:
    - image-fields.md
    - preview-audio.md
    - highlighting.md
  - aggregations.md
  - how-to-vectorize.md
  - filters-1.md
  - multi-vector-search-3.md
  - creating-a-dataset.md
  - jsonshower.md
- getting-started:
  - _notebooks:
    - Intro_to_Relevance_AI.ipynb
    - RelevanceAI-ReadMe-Quick-Feature-Tour.ipynb
  - example-applications:
    - _notebooks:
      - RelevanceAI-ReadMe-Multi-Vector-Search.ipynb
      - RelevanceAI-ReadMe-Text-Search-using-USE-VectorHub.ipynb
      - RelevanceAI-ReadMe-Text-to-Image-Search.ipynb
      - RelevanceAI-ReadMe-Question-Answering-using-USE-QA-Tensorflow-Hub.ipynb
    - quickstart-text-search.md
    - quickstart-question-answering.md
    - music-recommendation.md
    - quickstart-text-to-image-search.md
    - quickstart-multivector-search.md
  - vectors-and-vector-databases:
    - experimentation-workflow.md
    - what-are-vector-databases.md
    - what-are-vectors.md
    - why-experimentation-first.md
  - terminology:
    - documents-1.md
  - old-welcome.md
  - terminology.md
  - boilerplate.md
  - features.md
  - vectors-and-vector-databases.md
  - installation.md
  - welcome.md
  - quick-tour.md
  - quickstart.md
  - example-applications.md
  - quickstart-boilerplate.md
  - quickstart-1.md
  - "\u2618\uFE0F_Relevance_AI_Quickstart.md"
- search-features:
  - _notebooks:
    - RelevanceAI_hybrid_search.ipynb
    - RelevanceAI_Exact_Text_Matching.ipynb
  - exact-text-matching:
    - exact-word-search.md
  - text-and-vector-search-hybrid:
    - hybrid-search-1.md
  - diversity-search:
    - diversity-search-1.md
  - chunk-search-1:
    - advance-chunk-search.md
    - chunk-search.md
  - redirects:
    - vectorise-text-with-vectorhub.md
    - vectorise-images-with-vectorhub.md
  - combining-exact-text-with-vector-search.md
  - text-and-vector-search-hybrid.md
  - exact-text-matching.md
  - multi-vector-search-2-1.md
  - diversity-search.md
  - chunk-search-1.md
  - redirects.md
- comparator:
  - search-comparator:
    - set-up.md
    - search-comparison-and-evaluation.md
    - search-comparator-2.md
  - coming-soon-1.md
  - embedding-comparator.md
  - search-comparator.md
- clustering-features:
  - clustering:
    - _notebooks:
      - RelevanceAI-ReadMe-Kmeans-Clustering-Step-by-Step.ipynb
      - RelevanceAI-ReadMe-Custom-Clustering.ipynb
      - RelevanceAI-ReadMe-Clustering-Metadata.ipynb
      - RelevanceAI-ReadMe-Clustering-Aggregation.ipynb
      - RelevanceAI-ReadMe-Clustering-List-Furthest.ipynb
      - RelevanceAI-ReadMe-Kmeans-Clustering.ipynb
      - RelevanceAI-ReadMe-Clustering-List-Closest.ipynb
    - custom-clustering.md
    - cluster-aggregate.md
    - cluster-metadata.md
    - inserting-centroids.md
    - list-closest-to-centroids.md
    - quickstart-clustering.md
    - quickstart-k-means.md
    - list-furthest-from-centroids.md
  - cluster-evaluation:
    - _notebooks:
      - RelevanceAI-ReadMe-Cluster-Metrics.ipynb
      - RelevanceAI-ReadMe-Cluster-Distribution.ipynb
    - cluster-evaluate.md
    - cluster-plot.md
    - cluster-distribution.md
    - cluster-metrics.md
  - clustering.md
  - cluster-evaluation.md
- integrations:
  - coming-soon-2.md
- projector:
  - quickstart-visualize-your-vectors:
    - visualise-your-vectors-in-3d.md
    - color-by-category.md
    - adding-labels.md
    - add-clustering.md
  - coming-soon.md
  - quickstart-visualize-your-vectors.md
- dashboard:
  - saving-aggregation-queries-from-sdk.md
  - writing-aggregation-queries.md
version: v2.0.0-autoresolve-git-conflict
