categories:
  clustering-features:
    cluster-evaluation:
    - cluster-distribution
    - cluster-evaluate
    - cluster-metrics
    - cluster-plot
    clustering:
    - cluster-aggregate
    - cluster-metadata
    - custom-clustering
    - inserting-centroids
    - list-closest-to-centroids
    - list-furthest-from-centroids
    - quickstart-clustering
    - quickstart-k-means
  comparator:
    coming-soon-1: []
    embedding-comparator: []
    search-comparator:
    - search-comparator-2
    - search-comparison-and-evaluation
    - set-up
  dashboard:
    saving-aggregation-queries-from-sdk: []
    writing-aggregation-queries: []
  general-features:
    aggregations:
    - aggregation-quick-start
    - aggregations-1
    - creating-aggregation-metrics
    - grouping-the-data
    creating-a-dataset:
    - documents-with-chunked-data
    - ecommerce-example-dataset
    - insert-a-csv
    - insert-a-df
    - inserting-data
    - preparing-data-from-csv-pandas-df
    - project-and-dataset
    filters-1:
    - categories
    - combining-filters-and-vector-search
    - contains
    - date
    - exact_match
    - exact_match-1
    - exists
    - ids
    - multiple-filters
    - numeric
    - or
    - regex
    how-to-vectorize:
    - how-to-vectorize-text-using-vectorhub-transformers
    - how-to-vectorize-using-the-sdk
    - vectorize-images
    - vectorize-text
    - waiting-for-the-encoding-to-end
    jsonshower:
    - highlighting
    - image-fields
    - preview-audio
    multi-vector-search-3:
    - multi-vector-search-2
    - multi-vector-search-with
  getting-started:
    boilerplate: []
    example-applications:
    - music-recommendation
    - quickstart-multivector-search
    - quickstart-question-answering
    - quickstart-text-search
    - quickstart-text-to-image-search
    features: []
    installation: []
    old-welcome: []
    quick-tour: []
    quickstart: []
    quickstart-1: []
    quickstart-boilerplate: []
    relevance-ai-quickstart: []
    terminology:
    - documents-1
    vectors-and-vector-databases:
    - experimentation-workflow
    - what-are-vector-databases
    - what-are-vectors
    - why-experimentation-first
    welcome: []
  integrations:
    coming-soon-2: []
  other:
    data-privacy-policy: []
    sdk-reference: []
  projector:
    coming-soon: []
    quickstart-visualize-your-vectors:
    - add-clustering
    - adding-labels
    - color-by-category
    - visualise-your-vectors-in-3d
  search-features:
    chunk-search-1:
    - advance-chunk-search
    - chunk-search
    combining-exact-text-with-vector-search: []
    diversity-search:
    - diversity-search-1
    exact-text-matching:
    - exact-word-search
    multi-vector-search-2-1: []
    redirects:
    - vectorise-images-with-vectorhub
    - vectorise-text-with-vectorhub
    text-and-vector-search-hybrid:
    - hybrid-search-1
  theory-and-concepts:
    vectors-for-classification: []
    what-is-vector-search:
    - _applications-of-vectors
    - _limitations-of-vectors
    - how-to-vector-search
  use-cases:
    better-text-search:
    - better-text-search-chunk-search
    - better-text-search-diversified-search-results
    - better-text-search-prerequisites
    - better-text-search-with-hybrid
    - fine-grained-search-search-on-chunks-of-text-data
    - fine-grained-search-search-on-chunks-of-text-data-1
    - fine-grained-search-search-on-chunks-of-text-data-2
    - pure-word-matching-pure-vector-search-or-combination-of-both
    - pure-word-matching-pure-vector-search-or-combination-of-both-1
    - pure-word-matching-pure-vector-search-or-combination-of-both-2
    better-vector-visualisation:
    - prerequisites
    image-search:
    - image-similarity-search
    - text-to-image-search
    nlp-search-with-e-commerce: []
    vector-search:
    - filters
    - hybrid-search
    - multi-vector-search
    - vector-search-prerequisites
version: v2.0.0
