
name: ReadMe Update

on:
  push:
      branches: [ main ]
  pull_request:
  # workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    outputs:
      notebook-fpaths: ${{ steps.set-notebook-fpaths.outputs.notebook-fpaths }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          # cache: 'pip'

      - name: Cache Python deps
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-${{ env.pythonLocation }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.pythonLocation }}-pip-
            ${{ runner.os }}-${{ env.pythonLocation }}-

      - run: echo $PWD >> $GITHUB_PATH
      - name: Install requirements
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          python -c 'import sys; print(sys.path)'

      - name: Set ReadMe version as Github env var
        run: |
          README_VERSION=$(cat __version__)
          echo "README_VERSION=$README_VERSION" >> $GITHUB_ENV
          echo "GIT_BRANCH_VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Test for API keys in docs
        run: |
          python src/tests/detect_secrets.py -d -p docs

      - name: Update asset links
        run: |
          python -c 'import sys; print(sys.path)'
          python src/rdme_sync/build/update_asset_ref.py -d -p . -pn RelevanceAI -v $GIT_BRANCH_VERSION

      - name: Update semver ref
        run: |
          python src/rdme_sync/build/update_semver_ref.py -d -p . -pn RelevanceAI -v $README_VERSION

      - name: Building docs from docs_template
        run: |
          python src/rdme_sync/build/build_docs.py -d -p . -pn RelevanceAI -v $GIT_BRANCH_VERSION

      - id: set-notebook-fpaths
        name: Setting notebook fpath output
        run: |
          export NOTEBOOK_IGNORE=$(cat src/tests/notebook_ignore.txt)
          export NOTEBOOKS=$(find docs -type f -name "*.ipynb")
          export NOTEBOOK_FPATHS=$(for n in  ${NOTEBOOKS[@]}; do echo $n; done | grep -wv "$NOTEBOOK_IGNORE"  | jq -Rsc '. / "\n" - [""]')
          echo "::set-output name=notebook-fpaths::$NOTEBOOK_FPATHS"


  test-notebooks:
    name: Test ${{ matrix.notebook }}
    needs: build-docs
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest]
        python-version: [ '3.8' ]
        # python-version: [ '3.6', '3.7', '3.8', '3.9' ]
        notebook: ${{fromJSON(needs.build-docs.outputs.notebook-fpaths )}}
        include:
          - os: ubuntu-latest
            path: ~/.cache/pip
          # - os: macos-latest
          #   path: ~/Library/Caches/pip
          # - os: windows-latest
          #   path: ~\AppData\Local\pip\Cache
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          # cache: 'pip'
      - name: Cache Python deps
        uses: actions/cache@v2
        with:
          path: ${{ matrix.path }}
          key: ${{ runner.os }}-${{ env.pythonLocation }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.pythonLocation }}-pip-
            ${{ runner.os }}-${{ env.pythonLocation }}-

      - name: Install requirements
        run: |
          pip install --upgrade pip
          python -m pip install -e .[tests]
          jupyter kernelspec list

      - name: Test notebooks
        continue-on-error: true
        env:
          TEST_ACTIVATION_TOKEN: ${{ secrets.TEST_ACTIVATION_TOKEN }}
        run: |
          README_VERSION=$(cat __version__)
          echo "README_VERSION=$README_VERSION" >> $GITHUB_ENV
          python src/tests/test_notebooks.py -d -p . -pn RelevanceAI -v $README_VERSION --notebooks ${{ matrix.notebook }} -nm



  sync-readme-docs:
    needs: test-notebooks
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest]
        include:
          - os: ubuntu-latest
            path: ~/.cache/pip
          # - os: macos-latest
          #   path: ~/Library/Caches/pip
          # - os: windows-latest
          #   path: ~\AppData\Local\pip\Cache
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}

      - name: Sync ReadMe docs
        env:
          RELEVANCEAI_README_API_KEY: ${{ secrets.RELEVANCEAI_README_API_KEY }}
        run: |
          README_VERSION=$(cat __version__)
          export GITHUB_ACTIONS=false ## Turn off default debugging for rdme@^7.0.0
          ./src/sync_readme.sh true ./docs/ $README_VERSION

      # - name: Set ReadMe version as Github env var
      #   run: |
      #     README_VERSION=$(cat __version__)
      #     echo "README_VERSION=$README_VERSION" >> $GITHUB_ENV

      # - name: GitHub Action
      #   env:
      #     RELEVANCEAI_README_API_KEY: ${{ secrets.RELEVANCEAI_README_API_KEY }}
      #   uses: readmeio/rdme@7.0.2
      #   with:
      #     rdme: docs ./docs --key=$RELEVANCEAI_README_API_KEY --version=$README_VERSION


  # update-readme-main:
  #   needs: sync-readme-docs
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     matrix:
  #       os: [ ubuntu-latest]
  #       include:
  #         - os: ubuntu-latest
  #           path: ~/.cache/pip
  #         # - os: macos-latest
  #         #   path: ~/Library/Caches/pip
  #         # - os: windows-latest
  #         #   path: ~\AppData\Local\pip\Cache
  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v2

  #   - uses: actions/setup-python@v2
  #     with:
  #       python-version: ${{ matrix.python-version }}
  #       cache: 'pip'

  #     - name: Sync ReadMe docs
  #       env:
  #         RELEVANCEAI_README_API_KEY: ${{ secrets.RELEVANCEAI_README_API_KEY }}
  #       run: |
  #         README_VERSION=$(cat __version__)
  #         echo "README_VERSION=$README_VERSION"
  #         ./src/sync_readme.sh true $README_VERSION

