
name: ReadMe Update

on:
  push:
      branches: [ main ]
  pull_request:
  # push:
  #   # branches: [ main, development ]
  # pull_request:
  #   # branches: [ main, development ]

  # workflow_dispatch:

jobs:
  test-notebooks:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest]
        python-version: [ '3.7' ]
        # python-version: [ '3.6', '3.7', '3.8', '3.9' ]
        include:
          - os: ubuntu-latest
            path: ~/.cache/pip
          # - os: macos-latest
          #   path: ~/Library/Caches/pip
          # - os: windows-latest
          #   path: ~\AppData\Local\pip\Cache
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      # - name: Cache Python deps
      #   uses: actions/cache@v2
      #   with:
      #     path: ${{ matrix.path }}
      #     key: ${{ runner.os }}-${{ env.pythonLocation }}-pip-${{ hashFiles('colab_requirements.txt') }}
      #     restore-keys: |
      #       ${{ runner.os }}-${{ env.pythonLocation }}-pip-
      #       ${{ runner.os }}-${{ env.pythonLocation }}-

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Set ReadMe version as Github env
        run: |
          README_VERSION=$(cat __version__)
          echo "README_VERSION=$README_VERSION" >> $GITHUB_ENV

      - name: Test for API keys in docs
        run: |
          python scripts/detect_api_keys.py -d True -p .

      - name: Update docs_template to match Readme version
        run: |
          python scripts/update_docs_version.py -d True -p . -pn RelevanceAI -v $README_VERSION

      - name: Building docs from docs_template
        run: |
          python scripts/build_docs.py -d True -p . -pn RelevanceAI -v $README_VERSION

      - name: Test notebooks
        env:
          TEST_ACTIVATION_TOKEN: ${{ secrets.TEST_ACTIVATION_TOKEN }}
        run: |
          python scripts/test_notebooks.py -d True -p . -pn RelevanceAI -v $README_VERSION


  sync-readme-docs:
    needs: test-notebooks
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest]
        include:
          - os: ubuntu-latest
            path: ~/.cache/pip
          # - os: macos-latest
          #   path: ~/Library/Caches/pip
          # - os: windows-latest
          #   path: ~\AppData\Local\pip\Cache
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Sync ReadMe docs
        env:
          RELEVANCEAI_README_API_KEY: ${{ secrets.RELEVANCEAI_README_API_KEY }}
        run: |
          README_VERSION=$(cat __version__)
          echo "README_VERSION=$README_VERSION"
          ./scripts/sync_readme_docs.sh true $README_VERSION



  # update-readme-main:
  #   needs: sync-readme-docs
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     matrix:
  #       os: [ ubuntu-latest]
  #       include:
  #         - os: ubuntu-latest
  #           path: ~/.cache/pip
  #         # - os: macos-latest
  #         #   path: ~/Library/Caches/pip
  #         # - os: windows-latest
  #         #   path: ~\AppData\Local\pip\Cache
  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v2

  #   - uses: actions/setup-python@v2
  #     with:
  #       python-version: ${{ matrix.python-version }}
  #       cache: 'pip'

  #     - name: Sync ReadMe docs
  #       env:
  #         RELEVANCEAI_README_API_KEY: ${{ secrets.RELEVANCEAI_README_API_KEY }}
  #       run: |
  #         README_VERSION=$(cat __version__)
  #         echo "README_VERSION=$README_VERSION"
  #         ./scripts/sync_readme_docs.sh true $README_VERSION

