
name: ReadMe Update

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development]

  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest] 
        python-version: [ '3.7' ]
        # python-version: [ '3.6', '3.7', '3.8', '3.9' ]
        include:
          - os: ubuntu-latest
            path: ~/.cache/pip
          # - os: macos-latest
          #   path: ~/Library/Caches/pip
          # - os: windows-latest
          #   path: ~\AppData\Local\pip\Cache
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Dependencies
        run: npm install
      
      - name: Sync ReadMe docs
        run: npx rdme docs ./RelevanceAI-ReadMe-docs/v0.27.0 --version=v0.27.0 --key ${{ secrets.README_LOGIN_KEY }}  

      

      ### Given stable version of SDK

      ### Run through notebooks and execute end to end with current version

      ### Update README docs with current version, latest updates




      # - name: Set up Python
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: ${{ matrix.python-version }}
      # - name: Cache pip
      #   uses: actions/cache@v2
      #   with:
      #     path: ${{ matrix.path }}
      #     key: ${{ runner.os }}-${{ env.pythonLocation }}-pip-${{ hashFiles('setup.py') }}-${{ hashFiles('requirements-dev.txt') }}
      #     restore-keys: |
      #       ${{ runner.os }}-${{ env.pythonLocation }}-pip-
      #       ${{ runner.os }}-${{ env.pythonLocation }}-
      # - name: Run tests
      #   env:
      #     TEST_PROJECT: ${{ secrets.TEST_PROJECT }}
      #     TEST_API_KEY: ${{ secrets.TEST_API_KEY }}
      #   run: |
      #     python -c "import sys; print(sys.version)"
      #     python -m pip install -e .[tests]
      #     python -m pip install pytest-sugar
      #     python -m pip install pytest-rerunfailures
      #     python -m pytest --cov=relevanceai -vv -rs -x --reruns 5 --reruns-delay 1
